services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5433:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./back-end
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - back-end/.env
    volumes:
      - back-end:/src/usr/

  app_react:
    build: ./front-end
    container_name: app_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8080:8080
    volumes:
      - build_react:/var/www/html
    depends_on:
      - postgres
      - node
      - app_react

volumes:
  postgres-volume:
  build_react:
  back-end:
  